CREATE INDEX IDX_JOBB_SAK ON JOBB (SAK_ID);
CREATE INDEX IDX_JOBB_BEHANDLING ON JOBB (BEHANDLING_ID);
CREATE INDEX IDX_JOBB_SAK_BEHANDLING ON JOBB (SAK_ID, BEHANDLING_ID);
CREATE INDEX IDX_JOBB_BARE_STATUS ON JOBB (STATUS);
CREATE INDEX IDX_JOBB_TYPE ON JOBB (TYPE);
CREATE INDEX IDX_JOBB_STATUS_NESTE_KJORING ON JOBB (STATUS, NESTE_KJORING);
CREATE INDEX IDX_JOBB_NESTE_KJORING ON JOBB (NESTE_KJORING);
CREATE INDEX IDX_JOBB_NESTE_KJORING_SAK_BEHANDLING ON JOBB (SAK_ID, BEHANDLING_ID, NESTE_KJORING);
CREATE INDEX IDX_JOBB_HISTORIKK_BARE_STATUS ON JOBB_HISTORIKK (STATUS);
CREATE INDEX IDX_JOBB_HISTORIKK_TID ON JOBB_HISTORIKK (OPPRETTET_TID);
CREATE INDEX IDX_JOBB_HISTORIKK_JOBB_ID ON JOBB_HISTORIKK (JOBB_ID);

DROP INDEX UIDX_JOBB_STATUS_SAK_BEHANDLING_TYPE;