apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: statistikk
  namespace: aap
  labels:
    team: aap
    sub: statistikk

spec:
  ingresses:
    - https://aap-statistikk.intern.dev.nav.no  
  image: {{image}}
  strategy:
   type: Recreate
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /actuator/metrics
  azure:
    application:
      enabled: true
  liveness:
    path: /actuator/live
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 5
  readiness:
    path: /actuator/ready
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 5
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: behandlingsflyt
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: hendelser
    bigQueryDatasets:
      - name: tester
        cascadingDelete: true  # false for produksjon. Nå kan sletting gjøres ved å slette denne linja
        permission: READWRITE
  env:
    - name: INTEGRASJON_PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: INTEGRASJON_PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default