apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: statistikk
  namespace: aap
  labels:
    team: aap
    sub: statistikk

spec:
  ingresses:
    - https://aap-statistikk.intern.dev.nav.no  
  image: {{image}}
  strategy:
   type: Recreate
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
  prometheus:
    enabled: true
    path: /actuator/metrics
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: behandlingsflyt
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: hendelser
