apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: statistikk
  namespace: aap
  labels:
    team: aap
    sub: statistikk

spec:
  ingresses:
    - https://aap-statistikk.intern.dev.nav.no  
  image: {{image}}
  port: 8080
  ttl: 3h
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
  secureLogs:
    enabled: true
