isdev: true
pdl_url: pdl-api.dev-fss-pub.nais.io
pdl_scope: api://dev-fss.pdl.pdl-api/.default
postmottak_azp: 68642ce3-a231-4c82-b106-7a2f4ed899bc
behandlingsflyt_azp: 5b4656d2-e8f0-4df1-9e10-269133df697f
oppgave_azp: f915beea-b81f-4d34-b98b-d8b22bcc966f