apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: statistikk
  namespace: aap
  labels:
    team: aap
    sub: statistikk

spec:
  {{#if isdev}}
  ingresses:
    - https://aap-statistikk.intern.dev.nav.no
  {{/if}}
  image: {{image}}
  strategy:
   type: RollingUpdate
  port: 8080
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 500Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /actuator/metrics
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  liveness:
    path: /actuator/live
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 21
  accessPolicy:
    inbound:
      rules:
        - application: saksbehandling
        - application: behandlingsflyt
        - application: oppgave
        - application: postmottak-backend
        - application: paw-patrol
        {{#if isdev}}
        - application: saksbehandling-lokal # For lokal utvikling. IKKE kopier denne til prod.yaml
        - application: azure-token-generator # Ikke i prod :)
          namespace: nais
          cluster: dev-gcp
        {{/if}}
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: {{pdl_url}}
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: true
        pointInTimeRecovery: true
        databases:
          - name: hendelser
            users:
              - name: datastream
    bigQueryDatasets:
      - name: saksstatistikk
        permission: READWRITE
      - name: ytelsestatistikk
        permission: READWRITE

  env:
    - name: INTEGRASJON_PDL_URL
      value: https://{{pdl_url}}/graphql
    - name: INTEGRASJON_PDL_SCOPE
      value: {{pdl_scope}}
    - name: INTEGRASJON_POSTMOTTAK_AZP
      value: {{postmottak_azp}}
    - name: INTEGRASJON_BEHANDLINGSFLYT_AZP
      value: {{behandlingsflyt_azp}}
    - name: INTEGRASJON_OPPGAVE_AZP
      value: {{oppgave_azp}}
    - name: HACKY_DELAY
      value: "20"
    - name: ENHET_RETRY_MAX_RETRIES
      value: "3"
    - name: ENHET_RETRY_DELAY_SECONDS
      value: "60"
    - name: JDK_JAVA_OPTIONS
      value: "-XX:+UseParallelGC -XX:ActiveProcessorCount=4"
