apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: statistikk
  namespace: aap
  labels:
    team: aap
    sub: statistikk

spec:
  {{#if isdev}}
  ingresses:
    - https://aap-statistikk.intern.dev.nav.no
  {{/if}}
  image: {{image}}
  strategy:
   type: RollingUpdate
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: "1"
      memory: 1024Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /actuator/metrics
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  liveness:
    path: /actuator/live
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 5
  readiness:
    path: /actuator/ready
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 5
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: saksbehandling
        - application: behandlingsflyt
        - application: oppgave
        - application: postmottak-backend
        - application: paw-patrol
        {{#if isdev}}
        - application: saksbehandling-lokal # For lokal utvikling. IKKE kopier denne til prod.yaml
        - application: azure-token-generator # Ikke i prod :)
          namespace: nais
          cluster: dev-gcp
        {{/if}}
    outbound:
      external:
        - host: {{pdl_url}}
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: true
        pointInTimeRecovery: true
        databases:
          - name: hendelser
    bigQueryDatasets:
      - name: saksstatistikk
        permission: READWRITE
      - name: ytelsestatistikk
        permission: READWRITE

  env:
    - name: INTEGRASJON_PDL_URL
      value: https://{{pdl_url}}/graphql
    - name: INTEGRASJON_PDL_SCOPE
      value: {{pdl_scope}}
