apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: view-behandlinger
  namespace: aap
  labels:
    team: aap
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: absent
    cnrm.cloud.google.com/project-id: {{project}}
spec:
  resourceID: view_behandlinger
  description: "View som viser behandlingsdata."
  datasetRef:
    external: ytelsestatistikk
  view:
    useLegacySql: false
    query: >-
     WITH
       rettighetstyper AS (
       SELECT
         r.id,
         r.behandling_id,
         ARRAY_AGG(struct(fra_dato, til_dato, rettighetstype)) AS perioder
       FROM
         `datastream_hendelser.public_rettighetstype` r
       JOIN
         `datastream_hendelser.public_rettighetstypeperioder` rp
       ON
         r.id = rp.rettighetstype_id
       GROUP BY
         r.id,
         r.behandling_id)
     SELECT
       s.saksnummer AS saksnummer,
       br.referanse AS behandlingsreferanse,
       b.type AS behandlingsType,
       b.opprettet_tid AS behandling_opprettet_tid,
       ARRAY_TO_STRING(ARRAY(
         SELECT
           JSON_VALUE(value)
         FROM
           UNNEST(JSON_EXTRACT_ARRAY(b.aarsaker_til_behandling)) AS value ), ', ' ) AS behandling_aarsak,
       p.ident AS brukerFnr,
       bh.resultat as behandlingsresultat,
       bh.vedtak_tidspunkt as vedtak_tidspunkt,
       bh.utbetaling_id AS utbetaling_id,
       d.kodeverk AS diagnose_kodeverk,
       d.diagnosekode AS diagnose_kode,
       d.bidiagnoser AS bidiagnoser_kode,
       rettighetstyper.perioder AS rettighetstype,
       ARRAY(
           SELECT fra_dato
           FROM `datastream_hendelser.public_arbeidsopptrappingperioder`
           WHERE behandling_id = b.id
           GROUP BY fra_dato
         ) AS perioder_med_arbeidsopptrapping,
       DATETIME(
           timestamp_millis(
             greatest(
               b.datastream_metadata.source_timestamp,
               bh.datastream_metadata.source_timestamp,
               br.datastream_metadata.source_timestamp,
               s.datastream_metadata.source_timestamp,
               ifnull(d.datastream_metadata.source_timestamp, 0))),
           'Europe/Oslo') AS rad_endret_tid,
       concat(b.id, '-', bh.id, '-', br.id, '-', s.id, '-', ifnull(cast(d.id as string), '')) AS unik_id
     FROM
       `datastream_hendelser.public_behandling` b
     JOIN
       `datastream_hendelser.public_sak` s
     ON
       b.sak_id = s.id
     JOIN
       `datastream_hendelser.public_behandling_referanse` br
     ON
        b.referanse_id = br.id
     JOIN
       `datastream_hendelser.public_behandling_historikk` bh
     ON
       bh.behandling_id = b.id
     JOIN
       `datastream_hendelser.public_person` p
     ON
       p.id = s.person_id
     LEFT JOIN
       `datastream_hendelser.public_diagnose` d
     ON
       d.behandling_id = b.id
     JOIN
       rettighetstyper
     ON
       rettighetstyper.behandling_id = b.id
     WHERE
       bh.gjeldende = TRUE
       AND (bh.slettet IS FALSE
         OR bh.slettet IS NULL )
       AND bh.status = 'AVSLUTTET'
       AND (bh.resultat NOT IN ('TRUKKET',
           'KLAGE_TRUKKET')
         OR bh.resultat IS NULL)
       AND b.type NOT IN ('Oppfølgingsbehandling')
    
