apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: view-utbetalinger
  namespace: aap
  labels:
    team: aap
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: absent
    cnrm.cloud.google.com/project-id: {{project}}
spec:
  resourceID: view_utbetalinger
  description: "View som viser utbetalingsrelatert data."
  datasetRef:
    external: ytelsestatistikk
  view:
    useLegacySql: false
    query: >-
      SELECT
        s.saksnummer AS saksnummer,
        br.referanse AS behandlingsreferanse,
        p.ident AS brukerFnr,
        b.type AS behandling_type,
        b.opprettet_tid AS behandling_opprettet_tid,
        bh.utbetaling_id AS utbetaling_id,
        bh.oppdatert_tid as oppdatert_tid
      FROM
        `datastream_hendelser.public_behandling` b
      JOIN
        `datastream_hendelser.public_sak` s
      ON
        b.sak_id = s.id
      JOIN
        `datastream_hendelser.public_behandling_referanse` br
      ON
        b.referanse_id = br.id
      JOIN
        `datastream_hendelser.public_behandling_historikk` bh
      ON
        bh.behandling_id = b.id
      JOIN
        `datastream_hendelser.public_person` p
      ON
        p.id = s.person_id
      WHERE
        bh.gjeldende = TRUE
        AND (bh.slettet IS FALSE
          OR bh.slettet IS NULL )
        AND b.type IN ('Førstegangsbehandling',
          'Revurdering')
        AND bh.status = 'AVSLUTTET'
        AND (bh.resultat NOT IN ('TRUKKET',
            'KLAGE_TRUKKET')
          OR bh.resultat IS NULL)
        AND b.type NOT IN ('Oppfølgingsbehandling')
