apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: view-tilkjent-ytelse
  namespace: aap
  labels:
    team: aap
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: absent
    cnrm.cloud.google.com/project-id: {{project}}
spec:
  resourceID: view_tilkjent_ytelse
  description: "View som viser tilkjent ytelse."
  datasetRef:
    external: ytelsestatistikk
  view:
    useLegacySql: false
    query: >-
      SELECT
        s.saksnummer,
        br.referanse,
        tp.fra_dato as fraDato,
        tp.til_dato,
        tp.dagsats,
        tp.gradering,
        tp.antall_barn as antallBarn,
        tp.barnetillegg,
        tp.barnetillegg_sats as barnetilleggSats,
        tp.redusert_dagsats as redusertDagsats
      FROM
        `aap-dev-e48b.datastream_hendelser.public_tilkjent_ytelse_periode` tp
      JOIN
        `aap-dev-e48b.datastream_hendelser.public_tilkjent_ytelse` ty
      ON
        tp.tilkjent_ytelse_id = ty.id
      JOIN
        `aap-dev-e48b.datastream_hendelser.public_behandling` b
      ON
        ty.behandling_id = b.id
      JOIN
        `aap-dev-e48b.datastream_hendelser.public_behandling_referanse` br
      ON
        b.referanse_id = br.id
      JOIN
        `aap-dev-e48b.datastream_hendelser.public_sak` s
      ON
        b.sak_id = s.id
