apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: view-vilkarsresultat
  namespace: aap
  labels:
    team: aap
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: absent
    cnrm.cloud.google.com/project-id: {{project}}
spec:
  resourceID: view_vilkarsresultat
  description: "View som viser vilkårsresultat."
  datasetRef:
    external: ytelsestatistikk
  view:
    useLegacySql: false
    query: >-
      SELECT s.saksnummer                  as saksnummer,
             br.referanse                  as behandlingsreferanse,
             b.type                        as behandlingsType,
             v.vilkar_type                 as type,
             date(vp.fra_dato) as fraDato,
             date(vp.til_dato) as tilDato,
             vp.utfall         as utfall,
             greatest(b.datastream_metadata.source_timestamp, v.datastream_metadata.source_timestamp, vr.datastream_metadata.source_timestamp, vp.datastream_metadata.source_timestamp, br.datastream_metadata.source_timestamp, s.datastream_metadata.source_timestamp) AS endretTid,
             concat(b.id, '-', v.id, '-', vr.id, '-', vp.id, '-', br.id, '-', s.id) as unik_id
      FROM datastream_hendelser.public_vilkarsresultat vr
               LEFT JOIN `datastream_hendelser.public_vilkar` v ON vr.id = v.vilkarresult_id
               join `datastream_hendelser.public_vilkarsperiode` vp on v.id = vp.vilkar_id
               LEFT JOIN `datastream_hendelser.public_behandling` b on vr.behandling_id = b.id
               LEFT JOIN `datastream_hendelser.public_behandling_referanse` br on b.referanse_id = br.id
               LEFT JOIN `datastream_hendelser.public_sak` s on s.id = b.sak_id