apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: view-ateam-behandlinger
  namespace: aap
  labels:
    team: aap
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: absent
    cnrm.cloud.google.com/project-id: {{project}}
spec:
  resourceID: view_ateam_behandlinger
  description: "Dataprodukt for A-team. Viser én rad per behandling med gjeldende tilstand."
  datasetRef:
    external: ateam
  view:
    useLegacySql: false
    query: >-
      SELECT
        pi.ident AS fodselsnummer,
        br.referanse AS behandlingreferanse,
        s.saksnummer AS saksnummer,
        CAST(NULL AS INT64) AS kode67,
        CASE
          WHEN bh.resultat IN ('TRUKKET', 'AVBRUTT') THEN bh.resultat
          WHEN bh.vedtak_tidspunkt IS NOT NULL THEN 'FERDIGBEHANDLET'
          ELSE 'UNDER_BEHANDLING'
          END AS resultat,
        timestamp(datetime(bh.mottatt_tid), 'Europe/Oslo') AS mottatt_tid,
        timestamp(
          datetime(bh.vedtak_tidspunkt), 'Europe/Oslo') AS vedtak_tid,
        (
          SELECT
            timestamp(
              datetime(MIN(h.hendelsestidspunkt), 'Europe/Oslo'))
          FROM `datastream_hendelser.public_behandling_historikk` h
          WHERE
            h.behandling_id = b.id
            AND h.status = 'AVSLUTTET'
        ) AS ferdigbehandlet_tid,
        timestamp(datetime(bh.oppdatert_tid), 'Europe/Oslo') AS endret_tid,
        timestamp(datetime(bh.oppdatert_tid), 'Europe/Oslo') AS rad_opprettet,
        timestamp_millis(bh.datastream_metadata.source_timestamp) AS teknisk_tid,
      FROM
        `datastream_hendelser.public_behandling` b
      JOIN
        `datastream_hendelser.public_behandling_referanse` br
        ON b.referanse_id = br.id
      JOIN
        `datastream_hendelser.public_sak` s
        ON b.sak_id = s.id
      JOIN
        `datastream_hendelser.public_person` p
        ON p.id = s.person_id
      JOIN
        `datastream_hendelser.public_person_ident` pi
        ON
          pi.person_id = p.id
          AND pi.aktiv = TRUE
      JOIN
        `datastream_hendelser.public_behandling_historikk` bh
        ON bh.behandling_id = b.id
      WHERE
        bh.gjeldende = TRUE
        AND bh.slettet IS FALSE
        AND (
          b.aarsak_til_opprettelse = 'SØKNAD'
          OR 'SØKNAD' IN UNNEST(JSON_VALUE_ARRAY(b.aarsaker_til_behandling)))
        AND b.type IN ('Førstegangsbehandling', 'Revurdering')
