apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: view-saksstatistikk
  namespace: aap
  labels:
    team: aap
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: absent
    cnrm.cloud.google.com/project-id: {{project}}
spec:
  resourceID: view_saksstatistikk
  description: "View som viser saksstatistikk."
  datasetRef:
    external: saksstatistikk
  view:
    useLegacySql: false
    query: >-
      SELECT *
      FROM
         `datastream_hendelser.public_saksstatistikk`
