apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: view-gyldige-behandlinger
  namespace: aap
  labels:
    team: aap
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: absent
    cnrm.cloud.google.com/project-id: {{project}}
spec:
  resourceID: view_gyldige_behandlinger
  description: "View som filtrerer behandlinger til ytelsesstatistikk. Kun vedtatte innvilgede behandlinger er interessant. Brukes av andre views for konsistent filtrering."
  datasetRef:
    external: ytelsestatistikk
  view:
    useLegacySql: false
    query: >-
      SELECT
        b.id AS behandling_id,
        bh.id AS bh_id
      FROM
        `datastream_hendelser.public_behandling` b
      JOIN
        `datastream_hendelser.public_behandling_historikk` bh
      ON
        bh.behandling_id = b.id
      WHERE
        bh.gjeldende = TRUE
        AND (bh.slettet IS FALSE
          OR bh.slettet IS NULL)
        AND bh.status = 'AVSLUTTET'
        AND (bh.resultat NOT IN ('TRUKKET', 'AVBRUTT',
            'KLAGE_TRUKKET')
          OR bh.resultat IS NULL)
        AND b.type NOT IN ('Oppfølgingsbehandling')
