name: Deploy BigQuery Resources

on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
      project:
        required: true
        type: string

jobs:
  deploy-views:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: nais/deploy/actions/deploy@8a6fb62e73f837af6287d5db84a46ea96aa6c30d # v2
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: "\
            .nais/bigquery/view_gyldige_behandlinger.yml,\
            .nais/bigquery/view_vilkarsresultat.yml,\
            .nais/bigquery/view_tilkjent_ytelse.yml,\
            .nais/bigquery/view_beregningsgrunnlag.yml,\
            .nais/bigquery/view_saksstatistikk.yml,\
            .nais/bigquery/view_utbetaling.yml,\
            .nais/bigquery/view_meldekort.yml,\
            .nais/bigquery/view_samordning.yml,\
            .nais/bigquery/view_gjeldende_hendelser_saksstatistikk.yml,\
            .nais/bigquery/view_behandlinger_test.yml,\
            .nais/bigquery/view_behandlinger.yml"
          VAR: project=${{ inputs.project }}
          PRINT_PAYLOAD: true
