name: Deploy BigQuery Resources

on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
      project:
        required: true
        type: string

jobs:
  deploy-views:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: "\
            .nais/bigquery/view_vilkarsresultat.yml,\
            .nais/bigquery/view_tilkjent_ytelse.yml,\
            .nais/bigquery/view_beregningsgrunnlag.yml,\
            .nais/bigquery/view_saksstatistikk.yml,\
            .nais/bigquery/view_utbetaling.yml,\
            .nais/bigquery/view_behandlinger.yml"
          VAR: project=${{ inputs.project }}
          PRINT_PAYLOAD: true
