name: pr
on: pull_request

jobs:
  gradle:
    permissions:
      checks: write
      pull-requests: write
      actions: read
      contents: write
    uses: navikt/aap-workflows/.github/workflows/gradle-pr.yml@main
    secrets: inherit
