name: release

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: Cluster
        required: true
        default: dev-gcp
        type: choice
        options:
          - dev-gcp
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'

permissions:
  id-token: write

jobs:
  gradle:
    ## push til main eller etter branch (e.g. dependabot) er merget
    if: github.event.pull_request.merged || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
      actions: read
      checks: write
    uses: navikt/aap-workflows/.github/workflows/gradle-build.yml@main
    with:
      publish-typescript:  true
      typescript-enums: true
      generate-openapi-command: gradle genererOpenApi
      app-navn: statistikk
    secrets: inherit

  dev:
    ## push til main eller etter branch (e.g. dependabot) er merget
    if: github.event.pull_request.merged || github.event_name == 'push' || github.event.inputs.cluster == 'dev-gcp'
    permissions:
      contents: read
    needs: gradle
    uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      cluster: dev-gcp
      manifest: .nais/nais.yaml
      vars: .nais/dev.yaml

  prod:
    ## push til main eller etter branch (e.g. dependabot) er merget
    if: github.event.pull_request.merged || github.event_name == 'push' || github.event.inputs.cluster == 'prod-gcp'
    permissions:
      contents: read
    needs: dev
    uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      cluster: prod-gcp
      manifest: .nais/nais.yaml
      vars: .nais/prod.yaml

  deploy-bigquery-resources-dev:
    uses: ./.github/workflows/deploy_bigquery.yml
    secrets: inherit
    with:
      cluster: dev-gcp
      project: aap-dev-e48b