package no.nav.aap.statistikk.behandling

enum class Vurderingsbehov(val sortering: Int) {
    SØKNAD(0), HELHETLIG_VURDERING(1), AKTIVITETSMELDING(1), MELDEKORT(1), FRITAK_MELDEPLIKT(2), LEGEERKLÆRING(
        1
    ),
    AVVIST_LEGEERKLÆRING(1), DIALOGMELDING(1), G_REGULERING(1), REVURDER_MEDLEMSSKAP(1), REVURDER_YRKESSKADE(
        1
    ),
    REVURDER_BEREGNING(1), REVURDER_LOVVALG(1), REVURDER_MELDEPLIKT_RIMELIG_GRUNN(1), KLAGE(0), REVURDER_SAMORDNING(
        1
    ),
    LOVVALG_OG_MEDLEMSKAP(1), FORUTGAENDE_MEDLEMSKAP(1), SYKDOM_ARBEVNE_BEHOV_FOR_BISTAND(1), BARNETILLEGG(
        1
    ),
    INSTITUSJONSOPPHOLD(1), SAMORDNING_OG_AVREGNING(1), REFUSJONSKRAV(1), UTENLANDSOPPHOLD_FOR_SOKNADSTIDSPUNKT(
        1
    ),
    VURDER_RETTIGHETSPERIODE(1), SØKNAD_TRUKKET(0), REVURDER_MANUELL_INNTEKT(1), KLAGE_TRUKKET(1), MOTTATT_KABAL_HENDELSE(
        1
    ),
    OPPFØLGINGSOPPGAVE(0), AKTIVITETSPLIKT_11_7(1), AKTIVITETSPLIKT_11_9(1), EFFEKTUER_AKTIVITETSPLIKT(
        1
    ),
    EFFEKTUER_AKTIVITETSPLIKT_11_9(1), OVERGANG_UFORE(1), OVERGANG_ARBEID(1), DØDSFALL_BRUKER(1), DØDSFALL_BARN(
        1
    ),
    REVURDERING_AVBRUTT(
        0
    ),
    OPPHOLDSKRAV(1), REVURDER_STUDENT(1), REVURDER_SAMORDNING_ANDRE_FOLKETRYGDYTELSER(1), REVURDER_SAMORDNING_UFØRE(
        1
    ),
    REVURDER_SAMORDNING_ANDRE_STATLIGE_YTELSER(1), REVURDER_SAMORDNING_ARBEIDSGIVER(1), REVURDER_SAMORDNING_TJENESTEPENSJON(
        1
    ),
    REVURDER_SYKEPENGEERSTATNING(1), BARNETILLEGG_SATS_REGULERING(0), UTVID_VEDTAKSLENGDE(1), REVURDER_SYKESTIPEND(
        1
    ),
    MIGRER_RETTIGHETSPERIODE(
        1
    ), ETABLERING_EGEN_VIRKSOMHET(1);
}